Add golint in test
Signed-off-by: ChengTiesheng <chengtiesheng@huawei.com>

diff --git a/test b/test
--- a/test
+++ b/test
@@ -12,6 +12,7 @@ source ./build
 
 TESTABLE="plugins/ipam/dhcp"
 FORMATTABLE="$TESTABLE libcni pkg/ip pkg/ns pkg/invoke pkg/types pkg/ipam pkg/skel plugins/ipam/host-local plugins/main/bridge plugins/meta/flannel"
+LINT="./..."
 
 # user has not provided PKG override
 if [ -z "$PKG" ]; then
@@ -47,6 +48,15 @@ vetRes=$(go vet $TEST)
 if [ -n "${vetRes}" ]; then
 	echo -e "govet checking failed:\n${vetRes}"
 	exit 255
+fi
+
+echo "Success"
+
+echo "Checking golint..."
+lintRes=$(golint $LINT)
+if [ -n "${lintRes}" ]; then
+        echo -e "golint checking failed:\n${lintRes}"
+        exit 255
 fi
 
 echo "Success"
